// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc8y246nFDyAx8REGk1JsUa3KDS-RVV7I',
    appId: '1:519278320999:web:0da5e6ed5798aff16163c2',
    messagingSenderId: '519278320999',
    projectId: 'web-project-term2',
    authDomain: 'web-project-term2.firebaseapp.com',
    databaseURL: 'https://web-project-term2-default-rtdb.firebaseio.com',
    storageBucket: 'web-project-term2.appspot.com',
    measurementId: 'G-CET8QXGC4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFRm_3VidWftUUv5PDRDD1FyHBLCglmAc',
    appId: '1:519278320999:android:67a326c0786fae466163c2',
    messagingSenderId: '519278320999',
    projectId: 'web-project-term2',
    databaseURL: 'https://web-project-term2-default-rtdb.firebaseio.com',
    storageBucket: 'web-project-term2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXP5TSB4ehQ--MjF_A5EbLSx_3X1AKFfc',
    appId: '1:519278320999:ios:0b9734946ddae2ff6163c2',
    messagingSenderId: '519278320999',
    projectId: 'web-project-term2',
    databaseURL: 'https://web-project-term2-default-rtdb.firebaseio.com',
    storageBucket: 'web-project-term2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXP5TSB4ehQ--MjF_A5EbLSx_3X1AKFfc',
    appId: '1:519278320999:ios:0b9734946ddae2ff6163c2',
    messagingSenderId: '519278320999',
    projectId: 'web-project-term2',
    databaseURL: 'https://web-project-term2-default-rtdb.firebaseio.com',
    storageBucket: 'web-project-term2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc8y246nFDyAx8REGk1JsUa3KDS-RVV7I',
    appId: '1:519278320999:web:4da74e52445032536163c2',
    messagingSenderId: '519278320999',
    projectId: 'web-project-term2',
    authDomain: 'web-project-term2.firebaseapp.com',
    databaseURL: 'https://web-project-term2-default-rtdb.firebaseio.com',
    storageBucket: 'web-project-term2.appspot.com',
    measurementId: 'G-J2MGX0Y6LN',
  );
}
